spring:
  application:
    name = Validation
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/Validation
    #initialization-mode: always
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

#logging:
#  level:
#    org:
#      springframework:
#        jdbc.core:
#          JdbcTemplate: DEBUG
#          StatementCreatorUtils: TRACE